### ISSUE TITLE
Handle Bluetooth state/permission changes correctly

### ISSUE THREAD

**Issue by sandy-8925** [sandy-8925/BLExplorer#6]
- For Bluetooth APIs to work, Bluetooth atleast must be enabled, and sometimes Location too. Location permissions may also be needed.
- The app has to listen for changes to Bluetooth, Location setting and location permission changes and react correctly
- For example, the background device scanning code has to start/stop scanning based on these state changes (already implemented)
- The UI must also react accordingly - DeviceServiceExploreActivity and CharacteristicActivity must gracefully exit when Bluetooth is disabled (since they depend on working Bluetooth APIs to create a connection to the device and interact with it).

**Comment by sandy-8925** [comment]
So it seems that Bluetooth connection and interaction device works fine without location services or permission - it's only the Bluetooth scanning that requires location permissions and services to be enabled. That part is already handled properly by RxAndroidBle.

Also, if location (or any other permission) is denied, Android will kill the app process, so we don't have to worry about handling that scenario.

**Comment by ildar** [comment]
this all sounds like for recent versions of Android. I just hope you wont
drop older versions support. Thanks.

**Comment by sandy-8925** [comment]
> this all sounds like for recent versions of Android. I just hope you wont drop older versions support. Thanks.

No, I'm not planning to drop support for the older versions. It's just that we need to also support the newer versions properly (e.g location permissions requirement). Anyway, I've finally raised the target SDK version to API 23 (Android 6.0 Marshmallow). Will raise it soon, all the way to API 29.

**Comment by sandy-8925** [comment]
Finished implementing as of https://github.com/sandy-8925/BLExplorer/commit/995951f18c3562cd22a486d5f58e7975bb174100

**Comment by sandy-8925** [comment]
@ildar 

Also, wanted to inform you that I've done all of my new work in a new branch here - https://github.com/sandy-8925/BLExplorer/tree/modernization_v2

I doubt I'll be able to merge this upstream, since I've made a huge number of changes and ligi hasn't reviewed that initial change yet.
